on:
    workflow_dispatch:
        inputs: 
            url:
                description: 'URL of the website to test'
                required: true
                

jobs:
    axe-core-cli:
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 17
            - name: Install axe-core/cli
              run: npm i @axe-core/cli --location=global
            - name: Install chrome
              uses: browser-actions/setup-chrome@v1
            - name: Install chromedriver
              uses: nanasess/setup-chromedriver@v2
            - name: Test website
              run: axe ${{ github.event.inputs.url }}