on:
    workflow_dispatch:

jobs:
  parse-websites:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.website-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set websites matrix
        id: website-matrix
        run: echo "::set-output name=matrix::$(jq -c . < ./websites.json)"

  axe-core-cli:
    needs: parse-websites
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.parse-websites.outputs.matrix)}}
    steps: 
        - name: Checkout repository
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install axe-core/cli
          run: npm i @axe-core/cli -g
        - name: Install chromedriver
          uses: nanasess/setup-chromedriver@v2
        - name: Testing ${{ matrix.name }}
          run: axe ${{ matrix.url }} --chromedriver-path='/usr/local/bin/chromedriver'