name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: "20 12 * * 0"
  push:
    branches:
      - main
      - site-building # Can be deleted as soon as this branch is merged

jobs:
  build_site:
    defaults:
      run:
        working-directory: ./web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          # Need to disable caching for now, since this requires the pnpm-lock
          # file to be at the root of the repo.
          # cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: build
        run: |
          pnpm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          # this should match the `pages` option in your adapter-static options
          path: "web/build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
